# metric storages prywatne ip stats_node 
# appserv1 prywatne ip serverów apki
# appserv2
# 
#
#
#
#
#
---
- hosts: app_node
  become: yes
  vars:
    metrics_storages_ip: 172.31.24.67
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    java: java-1.8.0-openjdk
    user: carrent
  tasks:
  #- include_tasks: tasks/test.yml
  - include_tasks: tasks/os-dependencies.yml
  - include_tasks: tasks/manage-telegraf.yml
  
- hosts: proxy_node
  become: yes
  vars: 
    ngix_repo: nginx
    amazon_epel_repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    appserv_ip1: 172.31.23.201
    appserv_ip2: 172.31.16.139
  tasks: 
  - include_tasks: tasks/manage-ngix.yml
    
- hosts: stats_nodes
  become: yes
  vars:
    influxdb_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
  tasks:
  - include_tasks: tasks/stats.yml
 
- hosts: db_nodes
  become: yes
  vars:
    db_name: car_db
    db_user: "user_{{db_name}}"
    db_pwd: "1234"
  tasks:
  - include_tasks: tasks/manage-db.yml
