---

- name: install amazon epel
  yum:
    name: "{{amazon_epel_repo}}"
    state: present  
- name: install the nginx rpm from a remote repo
  yum:
    name: "{{ngix_repo}}"
    state: present    
- name: "place app cfg int place"
  template:
    src: templates/application.conf
    dest: /etc/nginx/conf.d/application.conf
- name: "start nginx"
  service:
    name: "nginx"
    state: restarted